### ISSUE TITLE
Comment section is invisible [Atom v1.14.0]

### ISSUE THREAD

**Issue by alunux** [NLKNguyen/base16-papercolor-light-syntax#2]
My theme setting's:
- UI Theme: Atom Material
- Syntax Theme: Base16 Papercolor Light

This is the screenshot when I highlight the comment:
![screenshot from 2017-02-10 08-24-16](https://cloud.githubusercontent.com/assets/10938708/22810298/74c6614e-ef6a-11e6-9fe2-4b8adc9bbca4.png)

This is the screenshot when the comment is invisible:
![screenshot from 2017-02-10 08-24-30](https://cloud.githubusercontent.com/assets/10938708/22810300/773c0f28-ef6a-11e6-9ee1-02a0ecdd16db.png)

Btw, thanks for the beautiful themes :smile:

**Comment by NLKNguyen** [comment]
@antonpaisov Could you please look into this?

**Comment by antonpaisov** [comment]
@NLKNguyen yes, I can see that issue with the latest update and I will look into it

**Comment by antonpaisov** [comment]
hey guys, sorry for the delay, totally forgot about the issue as I usually use the dark version and I've started switching to vim recently :)

Fixed the problem in #3

**Comment by alunux** [comment]
I have tested the PR and it works. Thank you very much @antonpaisov.

**Comment by NLKNguyen** [comment]
Thank @antonpaisov 😄

**Comment by antonpaisov** [comment]
@NLKNguyen can you please make a 1.0.1 release? 🙂

**Comment by NLKNguyen** [comment]
I accidentally published a minor release 1.1.0 instead of a patch release 1.0.1 :)
